import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { generateScriptSchema } from "@/lib/validations"

/**
 * POST /api/scripts/generate
 * Genera script usando AI (mock per ora, integrare con OpenAI/Claude)
 */
export async function POST(req: NextRequest) {
  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    // Validazione body
    const body = await req.json()
    const validated = generateScriptSchema.safeParse(body)

    if (!validated.success) {
      return NextResponse.json(
        { error: "Invalid data", details: validated.error.flatten() },
        { status: 400 }
      )
    }

    const { projectId, prompt, type, tone, duration } = validated.data

    // Verifica ownership progetto
    const project = await prisma.project.findFirst({
      where: { id: projectId, userId: session.user.id, deletedAt: null },
    })

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 })
    }

    // TODO: Integrare con AI provider (OpenAI, Claude, etc.)
    // Per ora generiamo uno script di esempio
    const generatedContent = generateMockScript(prompt, type, tone, duration)

    // Crea lo script generato
    const script = await prisma.script.create({
      data: {
        title: `Generated ${type.toLowerCase()}: ${prompt.slice(0, 50)}...`,
        content: generatedContent,
        type,
        status: "DRAFT",
        synopsis: prompt,
        notes: `Generated with AI\nTone: ${tone}\nRequested duration: ${duration || "not specified"} minutes`,
        projectId,
      },
    })

    return NextResponse.json(
      {
        data: script,
        meta: {
          generated: true,
          model: "mock-ai-model", // TODO: sostituire con modello reale
          promptTokens: prompt.length / 4, // stima
          completionTokens: generatedContent.length / 4,
        },
      },
      { status: 201 }
    )
  } catch (error) {
    console.error("POST /api/scripts/generate error:", error)
    return NextResponse.json(
      { error: "Failed to generate script" },
      { status: 500 }
    )
  }
}

// Mock generator - sostituire con chiamata AI reale
function generateMockScript(
  prompt: string,
  type: string,
  tone: string,
  duration?: number
): string {
  const toneDescriptors: Record<string, string> = {
    professional: "polished and professional",
    casual: "relaxed and conversational",
    dramatic: "intense and emotionally charged",
    humorous: "light-hearted and funny",
    documentary: "informative and factual",
  }

  const estimatedDuration = duration || Math.floor(Math.random() * 10 + 2)

  return `# ${type.toUpperCase()}: Generated Content

## Logline
${prompt}

## Synopsis
This is an AI-generated ${type.toLowerCase()} with a ${toneDescriptors[tone] || tone} tone.
The estimated runtime is approximately ${estimatedDuration} minutes.

## Content

FADE IN:

### SCENE 1 - INT. LOCATION - DAY

[AI-generated scene based on prompt: "${prompt}"]

The space opens before us. Light filters through windows, casting long shadows across the floor. This is where our story begins.

CHARACTER A enters, their expression suggesting the weight of what's to come.

CHARACTER A
(to themselves)
This changes everything...

### SCENE 2 - EXT. OUTDOOR LOCATION - DAY

The exterior shot establishes our world. The atmosphere is ${tone}.

CHARACTER B approaches with purpose.

CHARACTER B
We need to talk about what you saw.

### SCENE 3 - INT. DIFFERENT LOCATION - NIGHT

The climax of our ${estimatedDuration}-minute piece builds to this moment.

CHARACTER A and CHARACTER B face each other.

CHARACTER A
(quietly)
I've made my decision.

BLACKOUT.

## Notes
- Generated tone: ${tone}
- Type: ${type}
- Estimated duration: ${estimatedDuration} minutes
- Original prompt: "${prompt}"

---
*This script was generated by AI and requires human review and editing.*
`
}
